# Generated by Django 3.2.15 on 2022-11-19 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('view', '0012_alter_stream_categories_alter_stream_likes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trendingstream',
            name='ranking',
            field=models.IntegerField(default=101),
        ),
    ]
